### PR TITLE
Replace mocha with Jest, remove test directory from final build

### PR DESCRIPTION
**Pull request by slinkardbrandon**
**Resolves** #9 

Could you verify that I didn't mess up your travis CI & the coveralls implementation? 

The tests are working fine with the jest packages now, I modeled my re-implementation of coveralls after another project I'm a contributor on but I'm not sure how it'll work in this repository and I'm not quite sure how to test it.

### CODE REVIEW

**Comment by slinkardbrandon** [comment]
Edit: Looks like the CI still appears to work per the PR. Nice 🙌

**Comment by cainus** [comment]
nice work! thanks!  I'm going to mark this package as "not maintained" after I publish this.

**Comment by cainus** [comment]
I just published 1.2.1 with your change.

**Comment by slinkardbrandon** [comment]
Awesome thank you!

**Pull request merged**
